version: '3.2'
services:
  cypress:
    image: 'cypress/included:3.3.0'
    working_dir: /e2e
    volumes:
      - ./:/e2e
    entrypoint:
      - "cypress" 
      - "run"
      - "--record"
      - "--key"
      - "${CYPRESS_KEY}"
